### PR TITLE
Update toggle.js

### PR DESCRIPTION
**Pull request by remcoder**
Hi there!

Nice extension. I Googled for 'ReactiveVar toggle' hoping someone had already implemented it and fortunately you did :-)

I have a little suggestion btw. Why not throw an exception when a non-boolean value is being toggled? Attempting to toggle a non-boolean value is likely a bug after all.

cheers

### CODE REVIEW

**Comment by dferber90** [comment]
Hi, thank you for your pull request. Good suggestion. I've merge it and will publish to Atmosphere in a few minutes.

It seems we are the only two people using this package ;)

**Comment by remcoder** [comment]
Awesome! :)

**Comment by dferber90** [comment]
Version 2.0.0 is now live: https://atmospherejs.com/dferber/reactive-var-toggle

Enjoy :)

**Comment by remcoder** [comment]
:+1:

**Pull request merged**
